[package]
name = "builder-derive"
version = "0.1.0"
edition = "2021"
license = "ISC"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = { version = "1.0.86", features = ["full"] }
